sudo: required
group: edge
language: elixir
elixir:
  - 1.7.3
otp_release:
  - 21.1
services:
  - docker
script:
  - MIX_ENV=test mix test --warnings-as-errors
  - docker build -t codeclimate/codeclimate-credo .
